#@ load("@ytt:data", "data")

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: luanerizer
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 1
      containers:
      - name: luanerizer
        image: #@ data.values.image
        readinessProbe:
          httpGet:
            path: /healthz
        resources: {}
  traffic:
  #@ if data.values.canary.deploy:
  - latestRevision: true
    percent: 0
    tag: canary
  - percent: 100
    #@ if data.values.canary.previousRevision:
    revisionName: #@ data.values.canary.previousRevision
    #@ else:
    latestRevision: true
    #@ end
  #@ else:
  - latestRevision: true
    percent: 100
  #@ end
