#@ load("@ytt:data", "data")

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: luanerizer
spec:
  template:
    metadata:
      name: luanerizer-prod
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 1
      containers:
      - name: luanerizer
        image: #@ data.values.image
        readinessProbe:
          httpGet:
            path: /healthz
        resources: {}
  traffic:
  - revisionName: luanerizer-prod
    percent: 100
