#@ load("@ytt:data", "data")

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: luanerizer
  annotations:
    serving.knative.dev/creator: cbraa@vmware.com
spec:
  template:
    metadata:
      name: null
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 1
      containers:
      - name: luanerizer
        image: #@ data.values.image
        #! readinessProbe:
        #!   httpGet:
        #!     path: /healthz
        resources: {}
  traffic:
  - latestRevision: true
    percent: 100
